sudo: required
dist: trusty
services:
  - docker

language: go

# Make sure project can also be built on travis for clones of the repo
go_import_path: github.com/elastic/beats

env:
  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"
    - DOCKER_COMPOSE_VERSION=1.11.1
    - GO_VERSION="$(cat .go-version)"
    # Newer versions of minikube fail on travis, see: https://github.com/kubernetes/minikube/issues/2704
    - TRAVIS_MINIKUBE_VERSION=v0.25.2

jobs:
  include:
    # General checks
    - os: linux
      env: TARGETS="check"
      go: $GO_VERSION
      stage: check

    # Filebeat
    - os: linux
      go: $GO_VERSION
      stage: test


addons:
  apt:
    update: true
    packages:
      - python-virtualenv
      - libpcap-dev
      - xsltproc
      - libxml2-utils
      - libsystemd-journal-dev

before_install:
  - python --version
  - umask 022
  - chmod -R go-w $GOPATH/src/github.com/elastic/beats
  # Docker-compose installation
  - sudo rm /usr/local/bin/docker-compose || true
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - if [ $TRAVIS_OS_NAME = osx ]; then pip install virtualenv; fi


# Skips installations step
install: true

script:
  - cd x-pack/filebeat
  - make mage
  - mage update build unitTest integTest
