update-repos:
	bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=repositories.bzl%go_repositories -prune=true -build_file_proto_mode=disable_global

update:
	bazel run //:gazelle -- update
