---
description: Pipeline for parsing Suricata EVE logs

processors:
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'

  # Handle the different Suricata event types.
  - lowercase:
      field: suricata.eve.event_type
      ignore_missing: true
  - set:
      field: event.kind
      value: event
  - append:
      field: event.category
      value:
        - network
  ## Alert
  - set:
      if: ctx?.suricata?.eve?.event_type == "alert"
      field: event.kind
      value: alert
  - append:
      if: ctx?.suricata?.eve?.event_type == "alert"
      field: event.category
      value:
        - intrusion_detection
  ## Anomaly and Alert
  - lowercase:
      field: suricata.eve.app_proto
      ignore_missing: true
  - set:
      if: ctx?.suricata?.eve?.app_proto == "ftp-data"
      field: network.protocol
      value: ftp
  - set:
      if: >-
        ctx?.suricata?.eve?.app_proto != "failed" &&
        ctx?.suricata?.eve?.app_proto != "template" &&
        ctx?.suricata?.eve?.app_proto != "template-rust"
      field: network.protocol
      value: '{{suricata.eve.app_proto}}'
      ignore_empty_value: true
  ## HTTP
  - append:
      if: ctx?.suricata?.eve?.event_type == "http"
      field: event.category
      value:
        - web
  - append:
      if: ctx?.suricata?.eve?.event_type == "http"
      field: event.type
      value:
        - access
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "http"
      field: network.protocol
      value: http
  - set:
      if: ctx?.suricata?.eve?.event_type == "http" && ctx?.suricata?.eve?.http?.status < 400
      field: event.outcome
      value: success
  - set:
      if: ctx?.suricata?.eve?.event_type == "http" && ctx?.suricata?.eve?.http?.status >= 400
      field: event.outcome
      value: failure
  ## DNS
  - append:
      if: ctx?.suricata?.eve?.event_type == "dns"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "dns"
      field: network.protocol
      value: dns
  - pipeline:
      if: >-
        ctx?.network?.protocol == "dns"
      name: '{< IngestPipeline "dns" >}'
  ## FTP or FTP Data
  - append:
      if: ctx?.suricata?.eve?.event_type == "ftp" || ctx?.suricata?.eve?.event_type == "ftp_data"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "ftp" || ctx?.suricata?.eve?.event_type == "ftp_data"
      field: network.protocol
      value: ftp
  ## TLS
  - append:
      if: ctx?.suricata?.eve?.event_type == "tls"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "tls"
      field: network.protocol
      value: tls
  - pipeline:
      if: ctx?.network?.protocol == "tls"
      name: '{< IngestPipeline "tls" >}'
  ## TFTP
  - append:
      if: ctx?.suricata?.eve?.event_type == "tftp"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "tftp"
      field: network.protocol
      value: tftp
  ## SMB
  - append:
      if: ctx?.suricata?.eve?.event_type == "smb"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "smb"
      field: network.protocol
      value: smb
  ## SSH
  - append:
      if: ctx?.suricata?.eve?.event_type == "ssh"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "ssh"
      field: network.protocol
      value: ssh
  ## Flow
  - append:
      if: ctx?.suricata?.eve?.event_type == "flow"
      field: event.type
      value:
        - connection
  - append:
      if: ctx?.suricata?.eve?.flow?.state == "new"
      field: event.type
      value:
        - start
  - append:
      if: ctx?.suricata?.eve?.flow?.state == "closed"
      field: event.type
      value:
        - end
  ## RDP
  - append:
      if: ctx?.suricata?.eve?.event_type == "rdp"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "rdp"
      field: network.protocol
      value: rdp
  ## RFB (Remote Framebuffer Protocol)
  - append:
      if: ctx?.suricata?.eve?.event_type == "rfb"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "rfb"
      field: network.protocol
      value: rfb
  ## MQTT
  - append:
      if: ctx?.suricata?.eve?.event_type == "mqtt"
      field: event.type
      value:
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "mqtt"
      field: network.protocol
      value: mqtt
  ## HTTP2
  - append:
      if: ctx?.suricata?.eve?.event_type == "http2"
      field: event.category
      value:
        - web
  - append:
      if: ctx?.suricata?.eve?.event_type == "http2"
      field: event.type
      value:
        - access
        - protocol
  - set:
      if: ctx?.suricata?.eve?.event_type == "http2"
      field: network.protocol
      value: http2
  ## Stats
  - set:
      if: ctx?.suricata?.eve?.event_type == "stats"
      field: event.kind
      value: metric

  - set:
      value: "{{suricata.eve.http.http_method}}"
      field: http.request.method
      if: "ctx?.suricata?.eve?.http?.http_method != null"
  - rename:
      field: suricata.eve.http.status
      target_field: http.response.status_code
      ignore_missing: true
  - append:
      if: ctx.suricata?.eve?.http?.hostname != null
      value: '{{suricata.eve.http.hostname}}'
      field: destination.domain
      allow_duplicates: false
  - remove:
      field: suricata.eve.http.hostname
      ignore_failure: true
  - script:
      lang: painless
      tag: suricata_deduplicate_dest_domain
      source: >
        def domain = ctx.destination?.domain;
        if (domain instanceof Collection) {
          domain = domain.stream().distinct().collect(Collectors.toList());
          if (domain.length == 1) {
            domain = domain[0];
          }
          ctx.destination.domain = domain;
        }
      ignore_failure: true
  - set:
      if: "ctx?.network?.protocol == 'http'"
      field: url.domain
      value: '{{destination.domain}}'
      ignore_empty_value: true
  - grok:
      field: suricata.eve.http.url
      patterns:
        - '%{PATH:url.path}(?:\?%{QUERY:url.query})?(?:#%{ANY:url.fragment})?'
      ignore_missing: true
      pattern_definitions:
        PATH: '[^?#]*'
        QUERY: '[^#]*'
        ANY: '.*'
  - rename:
      field: suricata.eve.http.url
      target_field: url.original
      ignore_missing: true
  - rename:
      field: suricata.eve.http.http_refer
      target_field: http.request.referrer
      ignore_missing: true
  - rename:
      field: suricata.eve.http.length
      target_field: http.response.body.bytes
      ignore_missing: true
  - rename:
      field: suricata.eve.fileinfo.filename
      target_field: file.path
      ignore_missing: true
  - rename:
      field: suricata.eve.fileinfo.size
      target_field: file.size
      ignore_missing: true
  - lowercase:
      field: network.transport
      ignore_missing: true
  - convert:
      field: suricata.eve.alert.category
      target_field: message
      type: string
      ignore_missing: true
  - set:
      field: rule.category
      value: "{{suricata.eve.alert.category}}"
      ignore_empty_value: true
  - set:
      field: rule.id
      value: "{{suricata.eve.alert.signature_id}}"
      ignore_empty_value: true
  - set:
      field: rule.name
      value: "{{suricata.eve.alert.signature}}"
      ignore_empty_value: true
  - set:
      field: suricata.eve.alert.action
      value: denied
      if:  "ctx?.suricata?.eve?.alert?.action == 'blocked'"
  - append:
      field: event.type
      value: "{{suricata.eve.alert.action}}"
      if: "ctx?.suricata?.eve?.alert?.action != null"
  - remove:
      field: suricata.eve.alert.action
      ignore_failure: true
  - rename:
      field: suricata.eve.alert.severity
      target_field: event.severity
      ignore_missing: true
  - rename:
      field: suricata.eve.flow.pkts_toclient
      target_field: destination.packets
      ignore_missing: true
  - rename:
      field: suricata.eve.flow.pkts_toserver
      target_field: source.packets
      ignore_missing: true
  - rename:
      field: suricata.eve.flow.bytes_toclient
      target_field: destination.bytes
      ignore_missing: true
  - rename:
      field: suricata.eve.flow.bytes_toserver
      target_field: source.bytes
      ignore_missing: true
  - script:
      lang: painless
      source: >
        long getOrZero(def map, def key) {
          if (map!=null && map[key]!=null) {
            return map[key];
          }
          return 0;
        }
        def network=ctx['network'], source=ctx['source'], dest=ctx['destination'];
        def sp=getOrZero(source,'packets'), sb=getOrZero(source,'bytes'), dp=getOrZero(dest,'packets'), db=getOrZero(dest,'bytes');
        if (sb+db+sp+dp > 0) {
          if (network == null) {
            network=new HashMap();
            ctx['network']=network;
          }
          if (sb+db > 0) {
            network['bytes'] = sb+db;
          }
          if(sp+dp>0) {
            network['packets'] = sp+dp;
          }
        }
  - date:
      field: suricata.eve.flow.start
      target_field: event.start
      formats:
        - ISO8601
      ignore_failure: true
  - date:
      field: suricata.eve.flow.end
      target_field: event.end
      formats:
        - ISO8601
      ignore_failure: true
  - script:
      lang: painless
      source: >
        Instant ins(def d) {
          try {
            return Instant.parse(d);
          } catch(Exception e) {
            return null;
          }
        }
        def ev = ctx['event'];
        if (ev != null) {
          def start = ins(ev['start']);
          def end = ins(ev['end']);
          if (start != null && end != null && !start.isAfter(end)) {
            ev['duration'] = Duration.between(start,end).toNanos();
          }
        }
  - lowercase:
      field: suricata.eve.proto
      target_field: network.transport
      ignore_missing: true
  - user_agent:
      field: suricata.eve.http.http_user_agent
      ignore_missing: true
  - geoip:
      if: ctx.source?.geo == null
      field: source.ip
      target_field: source.geo
      ignore_missing: true
  - geoip:
      if: ctx.destination?.geo == null
      field: destination.ip
      target_field: destination.geo
      ignore_missing: true
  - geoip:
      database_file: GeoLite2-ASN.mmdb
      field: source.ip
      target_field: source.as
      properties:
        - asn
        - organization_name
      ignore_missing: true
  - geoip:
      database_file: GeoLite2-ASN.mmdb
      field: destination.ip
      target_field: destination.as
      properties:
        - asn
        - organization_name
      ignore_missing: true
  - rename:
      field: source.as.asn
      target_field: source.as.number
      ignore_missing: true
  - rename:
      field: source.as.organization_name
      target_field: source.as.organization.name
      ignore_missing: true
  - rename:
      field: destination.as.asn
      target_field: destination.as.number
      ignore_missing: true
  - rename:
      field: destination.as.organization_name
      target_field: destination.as.organization.name
      ignore_missing: true
  - append:
      field: related.hosts
      value: '{{url.domain}}'
      if: ctx.url?.domain != null && ctx.url?.domain != ''
      allow_duplicates: false
  - append:
      if: ctx?.source?.ip != null
      field: related.ip
      value: '{{source.ip}}'
      allow_duplicates: false
  - append:
      if: ctx?.destination?.ip != null
      field: related.ip
      value: '{{destination.ip}}'
      allow_duplicates: false
  - remove:
      field:
        - suricata.eve.app_proto
        - suricata.eve.flow.end
        - suricata.eve.flow.start
        - suricata.eve.http.http_method
        - suricata.eve.http.http_user_agent
      ignore_missing: true
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'
